### ISSUE TITLE
Ansible?

### ISSUE THREAD

**Issue by lierseleow** [AurelWeinhold/calm#13]
How to Install? How to configure?

How to use with Openstack and/or Kubernetes.

**Comment by Vrukshali-26** [comment]
To install ansible follow below steps : 
1. install python ( e.g. in rhel8 use : `yum install python3` )
2.  install ansible ( `pip3 install ansible` )
3.  extra : install sshpass ( e.g. in rhel8 use :  `yum install sshpass` )

Then check using `ansible --version`
