### ISSUE TITLE
failing to deploy when it tries to initialize fernet key authentication

### ISSUE THREAD

**Issue by lierseleow** [AurelWeinhold/calm#24]
When the deploy playbook tries to initialize the fernet key authentication, it fails, because the docker container is not ready.

This is because the container tries to restart and cant find python3.6, then crashes and restarts again.

We have to add python3.6 to the docker images or containers.

![dockerlogs](https://user-images.githubusercontent.com/69103048/103806098-d40c8f80-5054-11eb-8fdf-fade75fc5b09.PNG)

**Comment by AurelWeinhold** [comment]
Might be resolved by issue #26 with the rollback of the kolla-ansible version.
