### ISSUE TITLE
Telegram Bot for Notifications

### ISSUE THREAD

**Issue by marvin-steinke** [AurelWeinhold/calm#43]
As an admin I want to receive notifications regarding metrics through a telegram bot. This could probably be achieved through prometheus and the telegram api. The bot itself would be hosted by one of our servers.

**Comment by lierseleow** [comment]
https://prometheus.io/docs/operating/integrations/

**Comment by lierseleow** [comment]
https://github.com/inCaller/prometheus_bot

uses a telegram bot to send prometheus notifications to telegram groups.
